spring:
  datasource:
    url: jdbc:h2:mem:virtualMed
    username: sa
    password: password
    driverClassName: org.h2.Driver


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


springdoc:
  api-docs:
    path: /api/v1/auth

