spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/virtualMed
    username: postgres
    password: eden258
# Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # For formatting sql query in console




application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 3600000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


springdoc:
  api-docs:
    path: /api/v1/auth

