spring:
  data:
    mongodb:
      url: mongodb+srv://aseem:2003@cluster0.yxh8f.mongodb.net/virtualmed
      database: virtualmed

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
